### ISSUE TITLE
sitk or itk

### ISSUE THREAD

**Issue by tbaudier** [OpenGATE/GateTools#1]
Hi,

I check the @djboersma 's code and I saw you use SimpleITK. I just pushed a first version of gate_image_convert using python itk. Which one do we have to use? A first comparison is available here:
https://discourse.itk.org/t/should-i-switch-from-simpleitk-to-python-itk/1206/2

Thomas

**Comment by djboersma** [comment]
I just had a skype call with @dsarrut , David said he preferred itk over sitk for several reasons. I can try to rework my code to use itk instead.

**Comment by djboersma** [comment]
Also: @dsarrut suggested we could work directly on the master branch, we do not need to work on separate branches. So I am merging now and will continue on master.

**Comment by dsarrut** [comment]
After discussion : itk (not sitk)
