### ISSUE TITLE
itk and swapaxes

### ISSUE THREAD

**Issue by brenthuisman** [OpenGATE/GateTools#6]
In /gatetools/gamma_index.py I see that swapaxes is still used when taking the numpy arrays from the itk image object. In @djboersma [commit](https://github.com/OpenGATE/GateTools/commit/28dc92a12f5873c6843a30e080aef9ca67b877a6) where he replaces `SimpleITK` with `itk` one of the reasons was that this is no longer necesary (which is great!). So are the two remaining occurances of swapaxes a bug?

(Incidentally, not having to deal with swapaxes everywhere was half the reason I started `[medimage](https://github.com/brenthuisman/medimage)`!)

**Comment by djboersma** [comment]
Hi Brent, thanks for reviewing our code! When I wrote in a commit message that "swapaxes" is no longer needed, I was mistaken (I don't remember anymore what made me think that it wasn't needed). The arrays returned by `itk.array_from_image(img)` still have swapped axes. I could choose not to swap the axes to x-y-z order, but then I'd need to invert the order of the spacing values and of the origin coordinates, so the code is never really swapaxes-free. So I decided to keep it as it is. And once you know that axes are swapped, it's not a very big deal, I think.

**Comment by brenthuisman** [comment]
In medimage I handle this upon read and write, so that you never have to think about this issue, as a user. I'm not sure why, but in my experience, when you start treating the array (after swapaxes) as on object, with any volumetric edits (i.e. taking subregions) you still get wrong results.

In medimage I 'fixed' it as follows: upon read:
https://github.com/brenthuisman/medimage/blob/master/medimage/io_metaimage.py#L67
Upon write just swapaxes seems to be enough.

You could life this line if you wish.
