### ISSUE TITLE
Image arithm with scalar

### ISSUE THREAD

**Issue by tbaudier** [OpenGATE/GateTools#7]
To do an operation between images and scalars without using the binary (eg: directly with Python) we need to create an image containing this scalar value.

**Comment by djboersma** [comment]
We could maybe move line [89](https://github.com/OpenGATE/GateTools/blob/master/bin/gt_image_arithm#L89) till [99](https://github.com/OpenGATE/GateTools/blob/master/bin/gt_image_arithm#L99) into another `image_artihm` function?

**Comment by tbaudier** [comment]
I imagine another condition here: https://github.com/OpenGATE/GateTools/blob/master/gatetools/image_arithm.py#L86   

to check if the value is a scalar:
(not hasattr(N, '__len__')) and (not isinstance(N, str))

**Comment by tbaudier** [comment]
For the moment I did this:
https://github.com/OpenGATE/GateTools/commit/b78986b3fbd83805a6775797143498d1e8227dfe

I do not know if we can do it differently
