### ISSUE TITLE
gt_merge_root  issue

### ISSUE THREAD

**Issue by Ompsda** [OpenGATE/GateTools#74]
Hi, 

I am trying to use the 'gt_merge_root' command to merge multiple files. It seems there is a problem with the local variable "uproot''. I would correct it, but this is my first time using python. 

This is how I use the function:

gt_merge_root    -o merged.root -r -v --logfile log_merge

This is the error message I get:

File "/home/hamdi.m/.local/lib/python3.8/site-packages/gatetools/merge_root.py", line 49, in merge_root
    out = uproot.recreate(outputfile)
UnboundLocalError: local variable 'uproot' referenced before assignment

Thank you!
Mahdjoub

**Comment by dsarrut** [comment]
Hi, you probably should install the Python module named "uproot". Try `pip install uproot`

**Comment by Ompsda** [comment]
Now it works. Thank you so much.
