### ISSUE TITLE
pip3 install gatetools not working - readme.md missing

### ISSUE THREAD

**Issue by GitFuchs** [OpenGATE/GateTools#77]
Hi, 

when trying to install gatetools using
pip3 install gatetools
the installation process aborts with an error message.
FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'

Please find below the full output.

All the best,
Hermann

ip3 install gatetools
Defaulting to user installation because normal site-packages is not writeable
Collecting gatetools
  Downloading gatetools-0.11.3-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.1/114.1 KB 3.8 MB/s eta 0:00:00
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from gatetools) (0.4.4)
Requirement already satisfied: scipy in /home/hfuchs/.local/lib/python3.10/site-packages (from gatetools) (1.9.1)
Requirement already satisfied: uproot in /home/hfuchs/.local/lib/python3.10/site-packages (from gatetools) (4.3.5)
Requirement already satisfied: lz4 in /home/hfuchs/.local/lib/python3.10/site-packages (from gatetools) (4.0.2)
Requirement already satisfied: numpy in /home/hfuchs/.local/lib/python3.10/site-packages (from gatetools) (1.23.3)
Requirement already satisfied: tqdm in /home/hfuchs/.local/lib/python3.10/site-packages (from gatetools) (4.64.1)
Requirement already satisfied: matplotlib in /home/hfuchs/.local/lib/python3.10/site-packages (from gatetools) (3.6.0)
Requirement already satisfied: wget in /home/hfuchs/.local/lib/python3.10/site-packages (from gatetools) (3.2)
Requirement already satisfied: pydicom in /home/hfuchs/.local/lib/python3.10/site-packages (from gatetools) (2.3.0)
Requirement already satisfied: xxhash in /home/hfuchs/.local/lib/python3.10/site-packages (from gatetools) (3.0.0)
  Downloading gatetools-0.11.2-py3-none-any.whl (113 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.8/113.8 KB 15.9 MB/s eta 0:00:00
  Downloading gatetools-0.11.1-py3-none-any.whl (113 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.4/113.4 KB 11.1 MB/s eta 0:00:00
Collecting rt-utils
  Downloading rt_utils-1.2.5-py3-none-any.whl (18 kB)
Collecting gatetools
  Downloading gatetools-0.11.0-py3-none-any.whl (113 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.4/113.4 KB 12.9 MB/s eta 0:00:00
  Downloading gatetools-0.10.2-py3-none-any.whl (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.3/104.3 KB 11.9 MB/s eta 0:00:00
  Downloading gatetools-0.10.1-py3-none-any.whl (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.3/104.3 KB 7.6 MB/s eta 0:00:00
  Downloading gatetools-0.10.0-py3-none-any.whl (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 KB 10.5 MB/s eta 0:00:00
  Downloading gatetools-0.9.14-py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 KB 11.1 MB/s eta 0:00:00
  Downloading gatetools-0.9.13-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.9/98.9 KB 11.4 MB/s eta 0:00:00
Collecting uproot3
  Downloading uproot3-3.14.4-py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.5/117.5 KB 14.9 MB/s eta 0:00:00
Collecting gatetools
  Downloading gatetools-0.9.9-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.2/96.2 KB 11.1 MB/s eta 0:00:00
  Downloading gatetools-0.9.8-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.2/96.2 KB 11.0 MB/s eta 0:00:00
  Downloading gatetools-0.9.7-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.5/95.5 KB 10.3 MB/s eta 0:00:00
  Downloading gatetools-0.9.6-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.4/95.4 KB 17.1 MB/s eta 0:00:00
  Downloading gatetools-0.9.5-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.4/95.4 KB 10.9 MB/s eta 0:00:00
  Downloading gatetools-0.9.4.tar.gz (69 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.7/69.7 KB 7.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-xgswkzcm/gatetools_2a7dbdb0a77f4d708dd1a516b61cdd81/setup.py", line 3, in <module>
          with open("readme.md", "r") as fh:
      FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by tbaudier** [comment]
Hi,

Could you tell me the version of python and your OS you use please?

**Comment by GitFuchs** [comment]
Hi,

sure:
My versions:
Python 3.10.6
Ubuntu 22.04.1 LTS

I may have solved the issue. Apparently itk was causing problems. It did not compile using the default (pip3 install itk). Installing a pre-compiled binary via: 
pip3 install --upgrade --pre itk
and installing addtional tools:
sudo apt-get install python3-tk
sudo apt-get install python3-pil python3-pil.imagetk

Seems to have solved the issue.

All the best,
Hermann
