### ISSUE TITLE
enforcing python 3.x

### ISSUE THREAD

**Issue by djboersma** [OpenGATE/GateTools#8]
When `pip install gatetools` is run in an environment with python version 2, it should fail. It does indeed fail when I try it, but the error message does not seem to have to do anything with the python version. Instead it complains about "readme.md" being absent.

In `setup.py` we require just Python version 3, but we should maybe be more strict and require version >=3.6, because we use ["formatted string literals"](https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings), which were introduced in 3.6.

Maybe [this](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) is how we should go about this (add a line `python_requires='>=3.6`,' to the `setuptools.setup(...)` args), but I'm not sure.

**Comment by dsarrut** [comment]
I assume it is resolved now ...
